### ISSUE TITLE
[Question] Maybe a HTML issue?

### ISSUE THREAD

**Issue by CSharperMantle** [ChromeUniverse/ESP32-RGB#1]
I was surfing the code of this project when I came across these following lines:

https://github.com/ChromeUniverse/ESP32-RGB/blob/96343c33ddc0dd36cc413861052d58fc23a2a613/esp32_rgb.ino#L141-L146

It seemed to me that the `<head>` tag was not closed, and the beginning tag of `<body>` was not found. Is it made on purpose or by accident? I'd be happy if you could provide any information on this because I am curious about whether these HTML can be rendered correctly.

**Comment by qrno** [comment]
This code seems to be adapted from [this one](https://raw.githubusercontent.com/RuiSantosdotme/ESP32-Course/master/code/Servo/WiFi_Web_Server_Servo/WiFi_Web_Server_Servo.ino) and those tags seem to have been lost in the process.

**Comment by ChromeUniverse** [comment]
Yup, forget to include some tags while modifying [this example](https://raw.githubusercontent.com/RuiSantosdotme/ESP32-Course/master/code/WiFi_Web_Server_Outputs/WiFi_Web_Server_Outputs.ino) for my project. My bad.
Even with the missing tags, the HTML is interpreted correctly and it displays the R, G and B values on a webpage. I only really used this webpage feature for debugging, though.
